src/fetchers.js
=> fix(content): add params support

src/fetchers.js
=> fix(content): support `content.root` parameter

.eslintignore, .gitignore, package-lock.json, package.json, src/fetchers.js, src/index.js, src/race.js, test/fetchers.test.js, test/index.test.js, test/race.test.js
=> fix(index): improve error handling

src/fetchers.js, src/index.js, test/fetchers.test.js
=> fix(dynamic): handle selector properly when invoking action

src/fetchers.js, test/fetchers.test.js
=> fix(fetcher): only try to fetch 404.html for html requests

package-lock.json, package.json
=> Greenkeeper/snyk 1.192.3

package-lock.json, package.json
=> Greenkeeper/epsagon 1.29.0

package-lock.json, package.json
=> Greenkeeper/snyk 1.192.4

.snyk, package-lock.json, package.json, test/index.test.js
=> Greenkeeper/@adobe/helix pingdom status 1.4.4

src/index.js, test/index.test.js
=> feat(cache): add request header to disable the cache in response

package-lock.json, package.json
=> chore(package): link ci action during stage

src/index.js
=> fix(monitoring): hide Epsagon token from Epsagon

.circleci/config.yml, .snyk, README.md, package-lock.json, package.json, src/index.js
=> Rename to helix-dispatch

src/fetchers.js, test/fetchers.test.js
=> feat(fetchers): Support authenticated GitHub access

package-lock.json, package.json, src/fetchers.js, src/index.js, test/fetchers.test.js, test/index.test.js
=> fix(logging): hide GITHUB_TOKEN from action params

src/index.js, test/index.test.js
=> fix(logging): ensure proper loggin for 503 errors

src/index.js
=> fix(response): ensure sanitized action options in response

src/fetchers.js
=> feat(fetchers): remove `entry` param

package-lock.json, package.json, src/index.js, test/index.test.js
=> fix(epsagon): use helix-epsagon wrapper

src/fetchers.js, test/fetchers.test.js
=> fix(logging): do not log 40x responses as errors

src/fetchers.js, test/fetchers.test.js
=> feat(static): Incoming __ow_headers are not transferred to static actions

package-lock.json, package.json, src/fetchers.js, src/index.js, src/openwhisk.js, test/fetchers.test.js, test/index.test.js, test/openwhisk.test.js
=> feat(actions): propagate transaction id

src/fetchers.js, src/index.js, test/index.test.js
=> Handle 429 and 502

src/index.js, test/index.test.js
Fix #285 
I checked the anomalies and could not figure out how to reproduce or what triggers that state. I think we should do it in 2 steps: 
1. add some logs (current PR) 
2. wait for error to occur again, determine the faulty cases and enhance the code to return appropriate error messages
=> fix(dispatch): catch unexpected states

src/index.js, test/index.test.js
=> feat(dispatch): only lookup redirect after 404

src/fetchers.js, test/fetchers.test.js
=> feat(dispatch): use helix-static service

src/index.js, test/index.test.js
see https://github.com/adobe/helix-pages/issues/424
=> fix(dispatch): clarify CDN caching

package.json
=> fix(wsk): reduce concurrency to 40

test/postdeploy-preprod.test.js
=> test(preprod): add preprod test

src/redirects.js, src/utils.js, test/index.test.js
should solve this:
https://pages--adobe.hlx.live/static/ete/hero-posters/hero_ps_pr_two.png
=> fix: don't follow redirects

src/index.js, src/resolve-preferred.js, test/index.test.js
=> fix: only abort unused requests

package-lock.json, package.json, src/index.js, test/index.test.js, test/post-deploy.test.js
=> fix(dispatch): request with trailing dot should 404

src/utils.js, test/index.test.js
=> fix(dispatch): don't forward illegal connection headers

src/fetchers.js, test/fetchers.test.js
=> feat(core): don't use git-resolve-ref anymore

.circleci/config.yml, src/index.js, test/post-deploy-utils.js, test/post-deploy.test.js
=> feat(deploy): deploy to google

package-lock.json, package.json, src/index.js, src/redirects.js, test/index.test.js
=> fix: clean up x-error values

package-lock.json, package.json, src/index.js
=> feat(log): use universal-logger

package-lock.json, package.json, src/index.js, test/index.test.js
use invocation id instead of activation id in the response log entries for the invoked functions.
=> fix(dispatch): use invocation id
